map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/csilab/multi_robot_sim/maps/v1/v1_map.yaml"   # <- 실제 맵 YAML 경로로 교체

# (선택) 맵 저장 서버
map_saver_server:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

# 라이프사이클 (맵 계열만)
lifecycle_manager_map:
  ros__parameters:
    use_sim_time: True
    autostart: True
    bond_timeout: 2.0
    node_names: ["map_server", "map_saver_server"]
